// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (user_id, name, institution, type, currency, opening_balance, include_in_net_worth)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, institution, type, currency, opening_balance, include_in_net_worth, archived_at, created_at, updated_at
`

type CreateAccountParams struct {
	UserID            uuid.UUID
	Name              string
	Institution       string
	Type              string
	Currency          string
	OpeningBalance    int64
	IncludeInNetWorth bool
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Name,
		arg.Institution,
		arg.Type,
		arg.Currency,
		arg.OpeningBalance,
		arg.IncludeInNetWorth,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Institution,
		&i.Type,
		&i.Currency,
		&i.OpeningBalance,
		&i.IncludeInNetWorth,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, name, institution, type, currency, opening_balance, include_in_net_worth, archived_at, created_at, updated_at FROM accounts WHERE id = $1 AND user_id = $2
`

type GetAccountParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Institution,
		&i.Type,
		&i.Currency,
		&i.OpeningBalance,
		&i.IncludeInNetWorth,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT (a.opening_balance + COALESCE(sum(t.amount), 0))::bigint AS balance
FROM accounts a
LEFT JOIN transactions t ON t.account_id = a.id AND t.deleted_at IS NULL
WHERE a.id = $1 AND a.user_id = $2
GROUP BY a.opening_balance
`

type GetAccountBalanceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetAccountBalance(ctx context.Context, arg GetAccountBalanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, getAccountBalance, arg.ID, arg.UserID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const listAccountBalancesByUser = `-- name: ListAccountBalancesByUser :many
SELECT a.id, a.user_id, a.name, a.institution, a.type, a.currency, a.opening_balance, a.include_in_net_worth, a.archived_at, a.created_at, a.updated_at, (a.opening_balance + COALESCE(sum(t.amount), 0))::bigint AS balance
FROM accounts a
LEFT JOIN transactions t ON t.account_id = a.id AND t.deleted_at IS NULL
WHERE a.user_id = $1
GROUP BY a.id
ORDER BY a.created_at, a.id
`

type ListAccountBalancesByUserRow struct {
	Account Account
	Balance int64
}

func (q *Queries) ListAccountBalancesByUser(ctx context.Context, userID uuid.UUID) ([]ListAccountBalancesByUserRow, error) {
	rows, err := q.db.Query(ctx, listAccountBalancesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountBalancesByUserRow
	for rows.Next() {
		var i ListAccountBalancesByUserRow
		if err := rows.Scan(
			&i.Account.ID,
			&i.Account.UserID,
			&i.Account.Name,
			&i.Account.Institution,
			&i.Account.Type,
			&i.Account.Currency,
			&i.Account.OpeningBalance,
			&i.Account.IncludeInNetWorth,
			&i.Account.ArchivedAt,
			&i.Account.CreatedAt,
			&i.Account.UpdatedAt,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT id, user_id, name, institution, type, currency, opening_balance, include_in_net_worth, archived_at, created_at, updated_at FROM accounts WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListAccountsByUser(ctx context.Context, userID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Institution,
			&i.Type,
			&i.Currency,
			&i.OpeningBalance,
			&i.IncludeInNetWorth,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountArchived = `-- name: SetAccountArchived :one
UPDATE accounts SET archived_at = $3, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, institution, type, currency, opening_balance, include_in_net_worth, archived_at, created_at, updated_at
`

type SetAccountArchivedParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ArchivedAt *time.Time
}

func (q *Queries) SetAccountArchived(ctx context.Context, arg SetAccountArchivedParams) (Account, error) {
	row := q.db.QueryRow(ctx, setAccountArchived, arg.ID, arg.UserID, arg.ArchivedAt)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Institution,
		&i.Type,
		&i.Currency,
		&i.OpeningBalance,
		&i.IncludeInNetWorth,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $3, institution = $4, type = $5, currency = $6, opening_balance = $7, include_in_net_worth = $8, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, institution, type, currency, opening_balance, include_in_net_worth, archived_at, created_at, updated_at
`

type UpdateAccountParams struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Name              string
	Institution       string
	Type              string
	Currency          string
	OpeningBalance    int64
	IncludeInNetWorth bool
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Institution,
		arg.Type,
		arg.Currency,
		arg.OpeningBalance,
		arg.IncludeInNetWorth,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Institution,
		&i.Type,
		&i.Currency,
		&i.OpeningBalance,
		&i.IncludeInNetWorth,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
