// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (user_id, event_type, entity_type, entity_ids, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, event_type, entity_type, entity_ids, payload, created_at
`

type CreateAuditEventParams struct {
	UserID     *uuid.UUID
	EventType  string
	EntityType string
	EntityIds  []uuid.UUID
	Payload    []byte
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.UserID,
		arg.EventType,
		arg.EntityType,
		arg.EntityIds,
		arg.Payload,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.EntityType,
		&i.EntityIds,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEventsByUser = `-- name: ListAuditEventsByUser :many
SELECT id, user_id, event_type, entity_type, entity_ids, payload, created_at FROM audit_events WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListAuditEventsByUserParams struct {
	UserID *uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListAuditEventsByUser(ctx context.Context, arg ListAuditEventsByUserParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.EntityType,
			&i.EntityIds,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
