// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budgets.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const categoryMonthlySpending = `-- name: CategoryMonthlySpending :many
SELECT x.year, x.month, x.category_id, sum(x.spend)::bigint AS spending
FROM (
    SELECT extract(YEAR FROM t.date)::int AS year, extract(MONTH FROM t.date)::int AS month,
           t.category_id::uuid AS category_id, -t.amount AS spend
    FROM transactions t
    WHERE t.user_id = $1 AND t.deleted_at IS NULL AND t.category_id IS NOT NULL AND t.type <> 'transfer'
    UNION ALL
    SELECT extract(YEAR FROM t.date)::int, extract(MONTH FROM t.date)::int,
           s.category_id, -s.amount
    FROM transaction_splits s
    JOIN transactions t ON t.id = s.transaction_id
    WHERE s.user_id = $1 AND t.deleted_at IS NULL AND t.type <> 'transfer'
) x
GROUP BY x.year, x.month, x.category_id
`

type CategoryMonthlySpendingRow struct {
	Year       int32
	Month      int32
	CategoryID uuid.UUID
	Spending   int64
}

// Net spending per category per calendar month: parent transactions that carry
// a category plus split lines. Ledger amounts are signed (expense negative), so
// spending = -amount. Transfers are never categorized and are excluded.
func (q *Queries) CategoryMonthlySpending(ctx context.Context, userID uuid.UUID) ([]CategoryMonthlySpendingRow, error) {
	rows, err := q.db.Query(ctx, categoryMonthlySpending, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryMonthlySpendingRow
	for rows.Next() {
		var i CategoryMonthlySpendingRow
		if err := rows.Scan(
			&i.Year,
			&i.Month,
			&i.CategoryID,
			&i.Spending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAllocationHistory = `-- name: CreateAllocationHistory :one
INSERT INTO allocation_history (user_id, period_id, category_id, field, old_amount, new_amount)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, period_id, category_id, field, old_amount, new_amount, created_at
`

type CreateAllocationHistoryParams struct {
	UserID     uuid.UUID
	PeriodID   uuid.UUID
	CategoryID *uuid.UUID
	Field      string
	OldAmount  int64
	NewAmount  int64
}

func (q *Queries) CreateAllocationHistory(ctx context.Context, arg CreateAllocationHistoryParams) (AllocationHistory, error) {
	row := q.db.QueryRow(ctx, createAllocationHistory,
		arg.UserID,
		arg.PeriodID,
		arg.CategoryID,
		arg.Field,
		arg.OldAmount,
		arg.NewAmount,
	)
	var i AllocationHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PeriodID,
		&i.CategoryID,
		&i.Field,
		&i.OldAmount,
		&i.NewAmount,
		&i.CreatedAt,
	)
	return i, err
}

const createBudgetPeriod = `-- name: CreateBudgetPeriod :one
INSERT INTO budget_periods (user_id, year, month, currency, planned_income, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, year, month, currency, planned_income, notes, created_at, updated_at
`

type CreateBudgetPeriodParams struct {
	UserID        uuid.UUID
	Year          int32
	Month         int32
	Currency      string
	PlannedIncome int64
	Notes         string
}

func (q *Queries) CreateBudgetPeriod(ctx context.Context, arg CreateBudgetPeriodParams) (BudgetPeriod, error) {
	row := q.db.QueryRow(ctx, createBudgetPeriod,
		arg.UserID,
		arg.Year,
		arg.Month,
		arg.Currency,
		arg.PlannedIncome,
		arg.Notes,
	)
	var i BudgetPeriod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Month,
		&i.Currency,
		&i.PlannedIncome,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetAllocation = `-- name: GetBudgetAllocation :one
SELECT id, user_id, period_id, category_id, amount, rollover, created_at, updated_at FROM budget_allocations WHERE period_id = $1 AND category_id = $2 AND user_id = $3
`

type GetBudgetAllocationParams struct {
	PeriodID   uuid.UUID
	CategoryID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) GetBudgetAllocation(ctx context.Context, arg GetBudgetAllocationParams) (BudgetAllocation, error) {
	row := q.db.QueryRow(ctx, getBudgetAllocation, arg.PeriodID, arg.CategoryID, arg.UserID)
	var i BudgetAllocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PeriodID,
		&i.CategoryID,
		&i.Amount,
		&i.Rollover,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetPeriod = `-- name: GetBudgetPeriod :one
SELECT id, user_id, year, month, currency, planned_income, notes, created_at, updated_at FROM budget_periods WHERE user_id = $1 AND year = $2 AND month = $3
`

type GetBudgetPeriodParams struct {
	UserID uuid.UUID
	Year   int32
	Month  int32
}

func (q *Queries) GetBudgetPeriod(ctx context.Context, arg GetBudgetPeriodParams) (BudgetPeriod, error) {
	row := q.db.QueryRow(ctx, getBudgetPeriod, arg.UserID, arg.Year, arg.Month)
	var i BudgetPeriod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Month,
		&i.Currency,
		&i.PlannedIncome,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetPeriodByID = `-- name: GetBudgetPeriodByID :one
SELECT id, user_id, year, month, currency, planned_income, notes, created_at, updated_at FROM budget_periods WHERE id = $1 AND user_id = $2
`

type GetBudgetPeriodByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetBudgetPeriodByID(ctx context.Context, arg GetBudgetPeriodByIDParams) (BudgetPeriod, error) {
	row := q.db.QueryRow(ctx, getBudgetPeriodByID, arg.ID, arg.UserID)
	var i BudgetPeriod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Month,
		&i.Currency,
		&i.PlannedIncome,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestBudgetPeriodBefore = `-- name: LatestBudgetPeriodBefore :one
SELECT id, user_id, year, month, currency, planned_income, notes, created_at, updated_at FROM budget_periods
WHERE user_id = $1 AND (year < $2 OR (year = $2 AND month < $3))
ORDER BY year DESC, month DESC
LIMIT 1
`

type LatestBudgetPeriodBeforeParams struct {
	UserID uuid.UUID
	Year   int32
	Month  int32
}

func (q *Queries) LatestBudgetPeriodBefore(ctx context.Context, arg LatestBudgetPeriodBeforeParams) (BudgetPeriod, error) {
	row := q.db.QueryRow(ctx, latestBudgetPeriodBefore, arg.UserID, arg.Year, arg.Month)
	var i BudgetPeriod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Month,
		&i.Currency,
		&i.PlannedIncome,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllocationHistoryByPeriod = `-- name: ListAllocationHistoryByPeriod :many
SELECT id, user_id, period_id, category_id, field, old_amount, new_amount, created_at FROM allocation_history WHERE period_id = $1 AND user_id = $2 ORDER BY created_at
`

type ListAllocationHistoryByPeriodParams struct {
	PeriodID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) ListAllocationHistoryByPeriod(ctx context.Context, arg ListAllocationHistoryByPeriodParams) ([]AllocationHistory, error) {
	rows, err := q.db.Query(ctx, listAllocationHistoryByPeriod, arg.PeriodID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllocationHistory
	for rows.Next() {
		var i AllocationHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PeriodID,
			&i.CategoryID,
			&i.Field,
			&i.OldAmount,
			&i.NewAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllocationsByPeriod = `-- name: ListAllocationsByPeriod :many
SELECT id, user_id, period_id, category_id, amount, rollover, created_at, updated_at FROM budget_allocations WHERE period_id = $1 AND user_id = $2 ORDER BY created_at
`

type ListAllocationsByPeriodParams struct {
	PeriodID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) ListAllocationsByPeriod(ctx context.Context, arg ListAllocationsByPeriodParams) ([]BudgetAllocation, error) {
	rows, err := q.db.Query(ctx, listAllocationsByPeriod, arg.PeriodID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetAllocation
	for rows.Next() {
		var i BudgetAllocation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PeriodID,
			&i.CategoryID,
			&i.Amount,
			&i.Rollover,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllocationsWithRuleByUser = `-- name: ListAllocationsWithRuleByUser :many
SELECT a.period_id, a.category_id, a.amount, a.rollover, p.year, p.month, c.rollover_rule
FROM budget_allocations a
JOIN budget_periods p ON p.id = a.period_id
JOIN categories c ON c.id = a.category_id
WHERE a.user_id = $1
ORDER BY p.year, p.month, a.created_at
`

type ListAllocationsWithRuleByUserRow struct {
	PeriodID     uuid.UUID
	CategoryID   uuid.UUID
	Amount       int64
	Rollover     int64
	Year         int32
	Month        int32
	RolloverRule string
}

func (q *Queries) ListAllocationsWithRuleByUser(ctx context.Context, userID uuid.UUID) ([]ListAllocationsWithRuleByUserRow, error) {
	rows, err := q.db.Query(ctx, listAllocationsWithRuleByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllocationsWithRuleByUserRow
	for rows.Next() {
		var i ListAllocationsWithRuleByUserRow
		if err := rows.Scan(
			&i.PeriodID,
			&i.CategoryID,
			&i.Amount,
			&i.Rollover,
			&i.Year,
			&i.Month,
			&i.RolloverRule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetPeriodsByUser = `-- name: ListBudgetPeriodsByUser :many
SELECT id, user_id, year, month, currency, planned_income, notes, created_at, updated_at FROM budget_periods WHERE user_id = $1 ORDER BY year, month
`

func (q *Queries) ListBudgetPeriodsByUser(ctx context.Context, userID uuid.UUID) ([]BudgetPeriod, error) {
	rows, err := q.db.Query(ctx, listBudgetPeriodsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetPeriod
	for rows.Next() {
		var i BudgetPeriod
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Year,
			&i.Month,
			&i.Currency,
			&i.PlannedIncome,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudgetPeriod = `-- name: UpdateBudgetPeriod :one
UPDATE budget_periods SET planned_income = $3, notes = $4, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, year, month, currency, planned_income, notes, created_at, updated_at
`

type UpdateBudgetPeriodParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	PlannedIncome int64
	Notes         string
}

func (q *Queries) UpdateBudgetPeriod(ctx context.Context, arg UpdateBudgetPeriodParams) (BudgetPeriod, error) {
	row := q.db.QueryRow(ctx, updateBudgetPeriod,
		arg.ID,
		arg.UserID,
		arg.PlannedIncome,
		arg.Notes,
	)
	var i BudgetPeriod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Month,
		&i.Currency,
		&i.PlannedIncome,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBudgetAllocation = `-- name: UpsertBudgetAllocation :one
INSERT INTO budget_allocations (user_id, period_id, category_id, amount, rollover)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (period_id, category_id)
DO UPDATE SET amount = EXCLUDED.amount, rollover = EXCLUDED.rollover, updated_at = now()
RETURNING id, user_id, period_id, category_id, amount, rollover, created_at, updated_at
`

type UpsertBudgetAllocationParams struct {
	UserID     uuid.UUID
	PeriodID   uuid.UUID
	CategoryID uuid.UUID
	Amount     int64
	Rollover   int64
}

func (q *Queries) UpsertBudgetAllocation(ctx context.Context, arg UpsertBudgetAllocationParams) (BudgetAllocation, error) {
	row := q.db.QueryRow(ctx, upsertBudgetAllocation,
		arg.UserID,
		arg.PeriodID,
		arg.CategoryID,
		arg.Amount,
		arg.Rollover,
	)
	var i BudgetAllocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PeriodID,
		&i.CategoryID,
		&i.Amount,
		&i.Rollover,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
