// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (user_id, group_id, name, icon, color, budget_type, rollover_rule, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, group_id, name, icon, color, budget_type, rollover_rule, sort_order, archived_at, created_at, updated_at
`

type CreateCategoryParams struct {
	UserID       uuid.UUID
	GroupID      uuid.UUID
	Name         string
	Icon         string
	Color        string
	BudgetType   string
	RolloverRule string
	SortOrder    int32
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.UserID,
		arg.GroupID,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.BudgetType,
		arg.RolloverRule,
		arg.SortOrder,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.BudgetType,
		&i.RolloverRule,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCategoryGroup = `-- name: CreateCategoryGroup :one
INSERT INTO category_groups (user_id, name, sort_order)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, sort_order, archived_at, created_at, updated_at
`

type CreateCategoryGroupParams struct {
	UserID    uuid.UUID
	Name      string
	SortOrder int32
}

func (q *Queries) CreateCategoryGroup(ctx context.Context, arg CreateCategoryGroupParams) (CategoryGroup, error) {
	row := q.db.QueryRow(ctx, createCategoryGroup, arg.UserID, arg.Name, arg.SortOrder)
	var i CategoryGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1 AND user_id = $2
`

type DeleteCategoryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.UserID)
	return err
}

const deleteCategoryGroup = `-- name: DeleteCategoryGroup :exec
DELETE FROM category_groups WHERE id = $1 AND user_id = $2
`

type DeleteCategoryGroupParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteCategoryGroup(ctx context.Context, arg DeleteCategoryGroupParams) error {
	_, err := q.db.Exec(ctx, deleteCategoryGroup, arg.ID, arg.UserID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, user_id, group_id, name, icon, color, budget_type, rollover_rule, sort_order, archived_at, created_at, updated_at FROM categories WHERE id = $1 AND user_id = $2
`

type GetCategoryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.BudgetType,
		&i.RolloverRule,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriesByUser = `-- name: ListCategoriesByUser :many
SELECT id, user_id, group_id, name, icon, color, budget_type, rollover_rule, sort_order, archived_at, created_at, updated_at FROM categories WHERE user_id = $1 ORDER BY sort_order, created_at
`

func (q *Queries) ListCategoriesByUser(ctx context.Context, userID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.BudgetType,
			&i.RolloverRule,
			&i.SortOrder,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryGroupsByUser = `-- name: ListCategoryGroupsByUser :many
SELECT id, user_id, name, sort_order, archived_at, created_at, updated_at FROM category_groups WHERE user_id = $1 ORDER BY sort_order, created_at
`

func (q *Queries) ListCategoryGroupsByUser(ctx context.Context, userID uuid.UUID) ([]CategoryGroup, error) {
	rows, err := q.db.Query(ctx, listCategoryGroupsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryGroup
	for rows.Next() {
		var i CategoryGroup
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.SortOrder,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCategoryArchived = `-- name: SetCategoryArchived :exec
UPDATE categories SET archived_at = $3, updated_at = now() WHERE id = $1 AND user_id = $2
`

type SetCategoryArchivedParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ArchivedAt *time.Time
}

func (q *Queries) SetCategoryArchived(ctx context.Context, arg SetCategoryArchivedParams) error {
	_, err := q.db.Exec(ctx, setCategoryArchived, arg.ID, arg.UserID, arg.ArchivedAt)
	return err
}

const setCategoryGroupArchived = `-- name: SetCategoryGroupArchived :exec
UPDATE category_groups SET archived_at = $3, updated_at = now() WHERE id = $1 AND user_id = $2
`

type SetCategoryGroupArchivedParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ArchivedAt *time.Time
}

func (q *Queries) SetCategoryGroupArchived(ctx context.Context, arg SetCategoryGroupArchivedParams) error {
	_, err := q.db.Exec(ctx, setCategoryGroupArchived, arg.ID, arg.UserID, arg.ArchivedAt)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET group_id = $3, name = $4, icon = $5, color = $6, budget_type = $7, rollover_rule = $8, sort_order = $9, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, group_id, name, icon, color, budget_type, rollover_rule, sort_order, archived_at, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	GroupID      uuid.UUID
	Name         string
	Icon         string
	Color        string
	BudgetType   string
	RolloverRule string
	SortOrder    int32
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.UserID,
		arg.GroupID,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.BudgetType,
		arg.RolloverRule,
		arg.SortOrder,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.BudgetType,
		&i.RolloverRule,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategoryGroup = `-- name: UpdateCategoryGroup :one
UPDATE category_groups SET name = $3, sort_order = $4, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, sort_order, archived_at, created_at, updated_at
`

type UpdateCategoryGroupParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	SortOrder int32
}

func (q *Queries) UpdateCategoryGroup(ctx context.Context, arg UpdateCategoryGroupParams) (CategoryGroup, error) {
	row := q.db.QueryRow(ctx, updateCategoryGroup,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.SortOrder,
	)
	var i CategoryGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
