// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exports.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const exportAllocationsByUser = `-- name: ExportAllocationsByUser :many
SELECT a.id, a.user_id, a.period_id, a.category_id, a.amount, a.rollover, a.created_at, a.updated_at, p.year, p.month
FROM budget_allocations a
JOIN budget_periods p ON p.id = a.period_id
WHERE a.user_id = $1
ORDER BY p.year, p.month, a.created_at
`

type ExportAllocationsByUserRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	PeriodID   uuid.UUID
	CategoryID uuid.UUID
	Amount     int64
	Rollover   int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Year       int32
	Month      int32
}

func (q *Queries) ExportAllocationsByUser(ctx context.Context, userID uuid.UUID) ([]ExportAllocationsByUserRow, error) {
	rows, err := q.db.Query(ctx, exportAllocationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportAllocationsByUserRow
	for rows.Next() {
		var i ExportAllocationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PeriodID,
			&i.CategoryID,
			&i.Amount,
			&i.Rollover,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Year,
			&i.Month,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportAuditEventsByUser = `-- name: ExportAuditEventsByUser :many
SELECT id, user_id, event_type, entity_type, entity_ids, payload, created_at FROM audit_events WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ExportAuditEventsByUser(ctx context.Context, userID *uuid.UUID) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, exportAuditEventsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.EntityType,
			&i.EntityIds,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportGoalContributionsByUser = `-- name: ExportGoalContributionsByUser :many
SELECT id, user_id, goal_id, transaction_id, amount, contributed_on, notes, created_at FROM goal_contributions WHERE user_id = $1 ORDER BY contributed_on, created_at
`

func (q *Queries) ExportGoalContributionsByUser(ctx context.Context, userID uuid.UUID) ([]GoalContribution, error) {
	rows, err := q.db.Query(ctx, exportGoalContributionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoalContribution
	for rows.Next() {
		var i GoalContribution
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoalID,
			&i.TransactionID,
			&i.Amount,
			&i.ContributedOn,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportGoalsByUser = `-- name: ExportGoalsByUser :many
SELECT id, user_id, name, type, target_amount, target_date, category_id, account_id, archived_at, created_at, updated_at FROM goals WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ExportGoalsByUser(ctx context.Context, userID uuid.UUID) ([]Goal, error) {
	rows, err := q.db.Query(ctx, exportGoalsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.TargetAmount,
			&i.TargetDate,
			&i.CategoryID,
			&i.AccountID,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportNotificationsByUser = `-- name: ExportNotificationsByUser :many
SELECT id, user_id, type, title, body, action_url, dedupe_key, read_at, created_at FROM notifications WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ExportNotificationsByUser(ctx context.Context, userID uuid.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, exportNotificationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.ActionUrl,
			&i.DedupeKey,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportRecurringRulesByUser = `-- name: ExportRecurringRulesByUser :many
SELECT id, user_id, name, account_id, category_id, amount, frequency, custom_interval_days, next_due_date, reminder_lead_days, archived_at, created_at, updated_at, anchor_date FROM recurring_rules WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ExportRecurringRulesByUser(ctx context.Context, userID uuid.UUID) ([]RecurringRule, error) {
	rows, err := q.db.Query(ctx, exportRecurringRulesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringRule
	for rows.Next() {
		var i RecurringRule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.AccountID,
			&i.CategoryID,
			&i.Amount,
			&i.Frequency,
			&i.CustomIntervalDays,
			&i.NextDueDate,
			&i.ReminderLeadDays,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnchorDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportSplitsByUser = `-- name: ExportSplitsByUser :many
SELECT id, user_id, transaction_id, category_id, amount, memo, created_at, updated_at FROM transaction_splits WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ExportSplitsByUser(ctx context.Context, userID uuid.UUID) ([]TransactionSplit, error) {
	rows, err := q.db.Query(ctx, exportSplitsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionSplit
	for rows.Next() {
		var i TransactionSplit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TransactionID,
			&i.CategoryID,
			&i.Amount,
			&i.Memo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportTransactionTagsByUser = `-- name: ExportTransactionTagsByUser :many
SELECT tt.transaction_id, t.name
FROM transaction_tags tt
JOIN tags t ON t.id = tt.tag_id
WHERE tt.user_id = $1
ORDER BY tt.transaction_id, t.name
`

type ExportTransactionTagsByUserRow struct {
	TransactionID uuid.UUID
	Name          string
}

func (q *Queries) ExportTransactionTagsByUser(ctx context.Context, userID uuid.UUID) ([]ExportTransactionTagsByUserRow, error) {
	rows, err := q.db.Query(ctx, exportTransactionTagsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportTransactionTagsByUserRow
	for rows.Next() {
		var i ExportTransactionTagsByUserRow
		if err := rows.Scan(&i.TransactionID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportTransactionsByUser = `-- name: ExportTransactionsByUser :many

SELECT id, user_id, account_id, category_id, type, status, amount, date, payee, notes, reviewed, transfer_pair_id, recurring_rule_id, import_batch_id, deleted_at, created_at, updated_at FROM transactions WHERE user_id = $1 ORDER BY date, created_at
`

// Full-export queries. Unlike the feature list queries these include archived
// and soft-deleted rows: a data export must contain everything the user owns.
func (q *Queries) ExportTransactionsByUser(ctx context.Context, userID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, exportTransactionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Status,
			&i.Amount,
			&i.Date,
			&i.Payee,
			&i.Notes,
			&i.Reviewed,
			&i.TransferPairID,
			&i.RecurringRuleID,
			&i.ImportBatchID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
