// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (user_id, name, type, target_amount, target_date, category_id, account_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, type, target_amount, target_date, category_id, account_id, archived_at, created_at, updated_at
`

type CreateGoalParams struct {
	UserID       uuid.UUID
	Name         string
	Type         string
	TargetAmount int64
	TargetDate   *time.Time
	CategoryID   *uuid.UUID
	AccountID    *uuid.UUID
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.TargetAmount,
		arg.TargetDate,
		arg.CategoryID,
		arg.AccountID,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.TargetAmount,
		&i.TargetDate,
		&i.CategoryID,
		&i.AccountID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGoalContribution = `-- name: CreateGoalContribution :one
INSERT INTO goal_contributions (user_id, goal_id, transaction_id, amount, contributed_on, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, goal_id, transaction_id, amount, contributed_on, notes, created_at
`

type CreateGoalContributionParams struct {
	UserID        uuid.UUID
	GoalID        uuid.UUID
	TransactionID *uuid.UUID
	Amount        int64
	ContributedOn time.Time
	Notes         string
}

func (q *Queries) CreateGoalContribution(ctx context.Context, arg CreateGoalContributionParams) (GoalContribution, error) {
	row := q.db.QueryRow(ctx, createGoalContribution,
		arg.UserID,
		arg.GoalID,
		arg.TransactionID,
		arg.Amount,
		arg.ContributedOn,
		arg.Notes,
	)
	var i GoalContribution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoalID,
		&i.TransactionID,
		&i.Amount,
		&i.ContributedOn,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getGoal = `-- name: GetGoal :one
SELECT id, user_id, name, type, target_amount, target_date, category_id, account_id, archived_at, created_at, updated_at FROM goals WHERE id = $1 AND user_id = $2
`

type GetGoalParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetGoal(ctx context.Context, arg GetGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, getGoal, arg.ID, arg.UserID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.TargetAmount,
		&i.TargetDate,
		&i.CategoryID,
		&i.AccountID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGoalBalance = `-- name: GetGoalBalance :one
SELECT COALESCE(sum(amount), 0)::bigint AS balance
FROM goal_contributions
WHERE goal_id = $1 AND user_id = $2
`

type GetGoalBalanceParams struct {
	GoalID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetGoalBalance(ctx context.Context, arg GetGoalBalanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, getGoalBalance, arg.GoalID, arg.UserID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const listContributionsByGoal = `-- name: ListContributionsByGoal :many
SELECT id, user_id, goal_id, transaction_id, amount, contributed_on, notes, created_at FROM goal_contributions WHERE goal_id = $1 AND user_id = $2 ORDER BY contributed_on
`

type ListContributionsByGoalParams struct {
	GoalID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) ListContributionsByGoal(ctx context.Context, arg ListContributionsByGoalParams) ([]GoalContribution, error) {
	rows, err := q.db.Query(ctx, listContributionsByGoal, arg.GoalID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoalContribution
	for rows.Next() {
		var i GoalContribution
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoalID,
			&i.TransactionID,
			&i.Amount,
			&i.ContributedOn,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsByUser = `-- name: ListGoalsByUser :many
SELECT id, user_id, name, type, target_amount, target_date, category_id, account_id, archived_at, created_at, updated_at FROM goals WHERE user_id = $1 AND archived_at IS NULL ORDER BY created_at
`

func (q *Queries) ListGoalsByUser(ctx context.Context, userID uuid.UUID) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoalsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.TargetAmount,
			&i.TargetDate,
			&i.CategoryID,
			&i.AccountID,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGoalArchived = `-- name: SetGoalArchived :exec
UPDATE goals SET archived_at = $3, updated_at = now() WHERE id = $1 AND user_id = $2
`

type SetGoalArchivedParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ArchivedAt *time.Time
}

func (q *Queries) SetGoalArchived(ctx context.Context, arg SetGoalArchivedParams) error {
	_, err := q.db.Exec(ctx, setGoalArchived, arg.ID, arg.UserID, arg.ArchivedAt)
	return err
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET name = $3, type = $4, target_amount = $5, target_date = $6, category_id = $7, account_id = $8, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, type, target_amount, target_date, category_id, account_id, archived_at, created_at, updated_at
`

type UpdateGoalParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         string
	Type         string
	TargetAmount int64
	TargetDate   *time.Time
	CategoryID   *uuid.UUID
	AccountID    *uuid.UUID
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.TargetAmount,
		arg.TargetDate,
		arg.CategoryID,
		arg.AccountID,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.TargetAmount,
		&i.TargetDate,
		&i.CategoryID,
		&i.AccountID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
