// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createImportBatch = `-- name: CreateImportBatch :one
INSERT INTO import_batches (user_id, account_id, file_name, status, row_count)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, account_id, file_name, status, row_count, created_at, committed_at
`

type CreateImportBatchParams struct {
	UserID    uuid.UUID
	AccountID uuid.UUID
	FileName  string
	Status    string
	RowCount  int32
}

func (q *Queries) CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, createImportBatch,
		arg.UserID,
		arg.AccountID,
		arg.FileName,
		arg.Status,
		arg.RowCount,
	)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.FileName,
		&i.Status,
		&i.RowCount,
		&i.CreatedAt,
		&i.CommittedAt,
	)
	return i, err
}

const deleteTransactionsByImportBatch = `-- name: DeleteTransactionsByImportBatch :exec
DELETE FROM transactions WHERE import_batch_id = $1 AND user_id = $2
`

type DeleteTransactionsByImportBatchParams struct {
	ImportBatchID *uuid.UUID
	UserID        uuid.UUID
}

func (q *Queries) DeleteTransactionsByImportBatch(ctx context.Context, arg DeleteTransactionsByImportBatchParams) error {
	_, err := q.db.Exec(ctx, deleteTransactionsByImportBatch, arg.ImportBatchID, arg.UserID)
	return err
}

const getImportBatch = `-- name: GetImportBatch :one
SELECT id, user_id, account_id, file_name, status, row_count, created_at, committed_at FROM import_batches WHERE id = $1 AND user_id = $2
`

type GetImportBatchParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetImportBatch(ctx context.Context, arg GetImportBatchParams) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, getImportBatch, arg.ID, arg.UserID)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.FileName,
		&i.Status,
		&i.RowCount,
		&i.CreatedAt,
		&i.CommittedAt,
	)
	return i, err
}

const listImportBatchesByUser = `-- name: ListImportBatchesByUser :many
SELECT id, user_id, account_id, file_name, status, row_count, created_at, committed_at FROM import_batches WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListImportBatchesByUser(ctx context.Context, userID uuid.UUID) ([]ImportBatch, error) {
	rows, err := q.db.Query(ctx, listImportBatchesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportBatch
	for rows.Next() {
		var i ImportBatch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.FileName,
			&i.Status,
			&i.RowCount,
			&i.CreatedAt,
			&i.CommittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setImportBatchStatus = `-- name: SetImportBatchStatus :one
UPDATE import_batches SET status = $3, committed_at = $4, row_count = $5
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, account_id, file_name, status, row_count, created_at, committed_at
`

type SetImportBatchStatusParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Status      string
	CommittedAt *time.Time
	RowCount    int32
}

func (q *Queries) SetImportBatchStatus(ctx context.Context, arg SetImportBatchStatusParams) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, setImportBatchStatus,
		arg.ID,
		arg.UserID,
		arg.Status,
		arg.CommittedAt,
		arg.RowCount,
	)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.FileName,
		&i.Status,
		&i.RowCount,
		&i.CreatedAt,
		&i.CommittedAt,
	)
	return i, err
}
