// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Name              string
	Institution       string
	Type              string
	Currency          string
	OpeningBalance    int64
	IncludeInNetWorth bool
	ArchivedAt        *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type AllocationHistory struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	PeriodID   uuid.UUID
	CategoryID *uuid.UUID
	Field      string
	OldAmount  int64
	NewAmount  int64
	CreatedAt  time.Time
}

type AuditEvent struct {
	ID         uuid.UUID
	UserID     *uuid.UUID
	EventType  string
	EntityType string
	EntityIds  []uuid.UUID
	Payload    []byte
	CreatedAt  time.Time
}

type BudgetAllocation struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	PeriodID   uuid.UUID
	CategoryID uuid.UUID
	Amount     int64
	Rollover   int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type BudgetPeriod struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Year          int32
	Month         int32
	Currency      string
	PlannedIncome int64
	Notes         string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Category struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	GroupID      uuid.UUID
	Name         string
	Icon         string
	Color        string
	BudgetType   string
	RolloverRule string
	SortOrder    int32
	ArchivedAt   *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type CategoryGroup struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	SortOrder  int32
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Goal struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         string
	Type         string
	TargetAmount int64
	TargetDate   *time.Time
	CategoryID   *uuid.UUID
	AccountID    *uuid.UUID
	ArchivedAt   *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type GoalContribution struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	GoalID        uuid.UUID
	TransactionID *uuid.UUID
	Amount        int64
	ContributedOn time.Time
	Notes         string
	CreatedAt     time.Time
}

type ImportBatch struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	AccountID   *uuid.UUID
	FileName    string
	Status      string
	RowCount    int32
	CreatedAt   time.Time
	CommittedAt *time.Time
}

type ImportUploadDatum struct {
	BatchID   uuid.UUID
	UserID    uuid.UUID
	Header    []byte
	HasHeader bool
	Rows      []byte
	Mapping   []byte
	CreatedAt time.Time
}

type Notification struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Type      string
	Title     string
	Body      string
	ActionUrl string
	DedupeKey string
	ReadAt    *time.Time
	CreatedAt time.Time
}

type NotificationPreference struct {
	UserID       uuid.UUID
	Type         string
	Enabled      bool
	ThresholdPct *int16
	UpdatedAt    time.Time
}

type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type RecurringRule struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	Name               string
	AccountID          uuid.UUID
	CategoryID         uuid.UUID
	Amount             int64
	Frequency          string
	CustomIntervalDays *int32
	NextDueDate        time.Time
	ReminderLeadDays   int32
	ArchivedAt         *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	AnchorDate         time.Time
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	UserAgent string
	IpAddress string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Tag struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	CreatedAt time.Time
}

type Transaction struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	AccountID       uuid.UUID
	CategoryID      *uuid.UUID
	Type            string
	Status          string
	Amount          int64
	Date            time.Time
	Payee           string
	Notes           string
	Reviewed        bool
	TransferPairID  *uuid.UUID
	RecurringRuleID *uuid.UUID
	ImportBatchID   *uuid.UUID
	DeletedAt       *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type TransactionSplit struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	TransactionID uuid.UUID
	CategoryID    uuid.UUID
	Amount        int64
	Memo          string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type TransactionTag struct {
	TransactionID uuid.UUID
	TagID         uuid.UUID
	UserID        uuid.UUID
}

type User struct {
	ID                  uuid.UUID
	Email               string
	PasswordHash        string
	Name                string
	Locale              string
	TimeZone            string
	FirstDayOfWeek      int16
	DefaultCurrency     string
	FailedLoginAttempts int32
	LockedUntil         *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
}
