// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRecurringRule = `-- name: CreateRecurringRule :one
INSERT INTO recurring_rules (user_id, name, account_id, category_id, amount, frequency, custom_interval_days, next_due_date, anchor_date, reminder_lead_days)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, name, account_id, category_id, amount, frequency, custom_interval_days, next_due_date, reminder_lead_days, archived_at, created_at, updated_at, anchor_date
`

type CreateRecurringRuleParams struct {
	UserID             uuid.UUID
	Name               string
	AccountID          uuid.UUID
	CategoryID         uuid.UUID
	Amount             int64
	Frequency          string
	CustomIntervalDays *int32
	NextDueDate        time.Time
	AnchorDate         time.Time
	ReminderLeadDays   int32
}

func (q *Queries) CreateRecurringRule(ctx context.Context, arg CreateRecurringRuleParams) (RecurringRule, error) {
	row := q.db.QueryRow(ctx, createRecurringRule,
		arg.UserID,
		arg.Name,
		arg.AccountID,
		arg.CategoryID,
		arg.Amount,
		arg.Frequency,
		arg.CustomIntervalDays,
		arg.NextDueDate,
		arg.AnchorDate,
		arg.ReminderLeadDays,
	)
	var i RecurringRule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AccountID,
		&i.CategoryID,
		&i.Amount,
		&i.Frequency,
		&i.CustomIntervalDays,
		&i.NextDueDate,
		&i.ReminderLeadDays,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnchorDate,
	)
	return i, err
}

const getRecurringRule = `-- name: GetRecurringRule :one
SELECT id, user_id, name, account_id, category_id, amount, frequency, custom_interval_days, next_due_date, reminder_lead_days, archived_at, created_at, updated_at, anchor_date FROM recurring_rules WHERE id = $1 AND user_id = $2
`

type GetRecurringRuleParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetRecurringRule(ctx context.Context, arg GetRecurringRuleParams) (RecurringRule, error) {
	row := q.db.QueryRow(ctx, getRecurringRule, arg.ID, arg.UserID)
	var i RecurringRule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AccountID,
		&i.CategoryID,
		&i.Amount,
		&i.Frequency,
		&i.CustomIntervalDays,
		&i.NextDueDate,
		&i.ReminderLeadDays,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnchorDate,
	)
	return i, err
}

const listRecurringRulesByUser = `-- name: ListRecurringRulesByUser :many
SELECT id, user_id, name, account_id, category_id, amount, frequency, custom_interval_days, next_due_date, reminder_lead_days, archived_at, created_at, updated_at, anchor_date FROM recurring_rules WHERE user_id = $1 AND archived_at IS NULL ORDER BY next_due_date
`

func (q *Queries) ListRecurringRulesByUser(ctx context.Context, userID uuid.UUID) ([]RecurringRule, error) {
	rows, err := q.db.Query(ctx, listRecurringRulesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringRule
	for rows.Next() {
		var i RecurringRule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.AccountID,
			&i.CategoryID,
			&i.Amount,
			&i.Frequency,
			&i.CustomIntervalDays,
			&i.NextDueDate,
			&i.ReminderLeadDays,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnchorDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesDueBy = `-- name: ListRulesDueBy :many
SELECT id, user_id, name, account_id, category_id, amount, frequency, custom_interval_days, next_due_date, reminder_lead_days, archived_at, created_at, updated_at, anchor_date FROM recurring_rules
WHERE user_id = $1 AND archived_at IS NULL AND next_due_date <= $2
ORDER BY next_due_date
`

type ListRulesDueByParams struct {
	UserID      uuid.UUID
	NextDueDate time.Time
}

func (q *Queries) ListRulesDueBy(ctx context.Context, arg ListRulesDueByParams) ([]RecurringRule, error) {
	rows, err := q.db.Query(ctx, listRulesDueBy, arg.UserID, arg.NextDueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringRule
	for rows.Next() {
		var i RecurringRule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.AccountID,
			&i.CategoryID,
			&i.Amount,
			&i.Frequency,
			&i.CustomIntervalDays,
			&i.NextDueDate,
			&i.ReminderLeadDays,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnchorDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRecurringRuleArchived = `-- name: SetRecurringRuleArchived :exec
UPDATE recurring_rules SET archived_at = $3, updated_at = now() WHERE id = $1 AND user_id = $2
`

type SetRecurringRuleArchivedParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ArchivedAt *time.Time
}

func (q *Queries) SetRecurringRuleArchived(ctx context.Context, arg SetRecurringRuleArchivedParams) error {
	_, err := q.db.Exec(ctx, setRecurringRuleArchived, arg.ID, arg.UserID, arg.ArchivedAt)
	return err
}

const setRecurringRuleNextDue = `-- name: SetRecurringRuleNextDue :one
UPDATE recurring_rules SET next_due_date = $3, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, account_id, category_id, amount, frequency, custom_interval_days, next_due_date, reminder_lead_days, archived_at, created_at, updated_at, anchor_date
`

type SetRecurringRuleNextDueParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	NextDueDate time.Time
}

func (q *Queries) SetRecurringRuleNextDue(ctx context.Context, arg SetRecurringRuleNextDueParams) (RecurringRule, error) {
	row := q.db.QueryRow(ctx, setRecurringRuleNextDue, arg.ID, arg.UserID, arg.NextDueDate)
	var i RecurringRule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AccountID,
		&i.CategoryID,
		&i.Amount,
		&i.Frequency,
		&i.CustomIntervalDays,
		&i.NextDueDate,
		&i.ReminderLeadDays,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnchorDate,
	)
	return i, err
}

const setTransactionRecurringRule = `-- name: SetTransactionRecurringRule :one
UPDATE transactions SET recurring_rule_id = $3, updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, account_id, category_id, type, status, amount, date, payee, notes, reviewed, transfer_pair_id, recurring_rule_id, import_batch_id, deleted_at, created_at, updated_at
`

type SetTransactionRecurringRuleParams struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	RecurringRuleID *uuid.UUID
}

func (q *Queries) SetTransactionRecurringRule(ctx context.Context, arg SetTransactionRecurringRuleParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, setTransactionRecurringRule, arg.ID, arg.UserID, arg.RecurringRuleID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.Date,
		&i.Payee,
		&i.Notes,
		&i.Reviewed,
		&i.TransferPairID,
		&i.RecurringRuleID,
		&i.ImportBatchID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRecurringRule = `-- name: UpdateRecurringRule :one
UPDATE recurring_rules
SET name = $3, account_id = $4, category_id = $5, amount = $6, frequency = $7, custom_interval_days = $8, next_due_date = $9, anchor_date = $10, reminder_lead_days = $11, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, account_id, category_id, amount, frequency, custom_interval_days, next_due_date, reminder_lead_days, archived_at, created_at, updated_at, anchor_date
`

type UpdateRecurringRuleParams struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	Name               string
	AccountID          uuid.UUID
	CategoryID         uuid.UUID
	Amount             int64
	Frequency          string
	CustomIntervalDays *int32
	NextDueDate        time.Time
	AnchorDate         time.Time
	ReminderLeadDays   int32
}

func (q *Queries) UpdateRecurringRule(ctx context.Context, arg UpdateRecurringRuleParams) (RecurringRule, error) {
	row := q.db.QueryRow(ctx, updateRecurringRule,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.AccountID,
		arg.CategoryID,
		arg.Amount,
		arg.Frequency,
		arg.CustomIntervalDays,
		arg.NextDueDate,
		arg.AnchorDate,
		arg.ReminderLeadDays,
	)
	var i RecurringRule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AccountID,
		&i.CategoryID,
		&i.Amount,
		&i.Frequency,
		&i.CustomIntervalDays,
		&i.NextDueDate,
		&i.ReminderLeadDays,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnchorDate,
	)
	return i, err
}
