// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const monthlyCashFlow = `-- name: MonthlyCashFlow :many
SELECT extract(YEAR FROM t.date)::int AS year, extract(MONTH FROM t.date)::int AS month,
       coalesce(sum(t.amount) FILTER (WHERE t.amount > 0), 0)::bigint AS inflow,
       coalesce(sum(-t.amount) FILTER (WHERE t.amount < 0), 0)::bigint AS outflow,
       coalesce(sum(t.amount), 0)::bigint AS net
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.user_id = $1 AND t.deleted_at IS NULL
  AND a.currency = $2
  AND t.date BETWEEN $3 AND $4
GROUP BY 1, 2
ORDER BY 1, 2
`

type MonthlyCashFlowParams struct {
	UserID   uuid.UUID
	Currency string
	DateFrom time.Time
	DateTo   time.Time
}

type MonthlyCashFlowRow struct {
	Year    int32
	Month   int32
	Inflow  int64
	Outflow int64
	Net     int64
}

// Cash movement per calendar month across all transaction types, transfers
// and adjustments included: a transfer between two same-currency accounts
// nets to zero, while one crossing the currency boundary shows as real
// in/outflow for this currency.
func (q *Queries) MonthlyCashFlow(ctx context.Context, arg MonthlyCashFlowParams) ([]MonthlyCashFlowRow, error) {
	rows, err := q.db.Query(ctx, monthlyCashFlow,
		arg.UserID,
		arg.Currency,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyCashFlowRow
	for rows.Next() {
		var i MonthlyCashFlowRow
		if err := rows.Scan(
			&i.Year,
			&i.Month,
			&i.Inflow,
			&i.Outflow,
			&i.Net,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlyIncomeSpending = `-- name: MonthlyIncomeSpending :many

SELECT extract(YEAR FROM t.date)::int AS year, extract(MONTH FROM t.date)::int AS month,
       coalesce(sum(t.amount) FILTER (WHERE t.type = 'income'), 0)::bigint AS income,
       coalesce(sum(-t.amount) FILTER (WHERE t.type IN ('expense', 'refund')), 0)::bigint AS spending
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.user_id = $1 AND t.deleted_at IS NULL
  AND a.currency = $2
  AND t.date BETWEEN $3 AND $4
GROUP BY 1, 2
ORDER BY 1, 2
`

type MonthlyIncomeSpendingParams struct {
	UserID   uuid.UUID
	Currency string
	DateFrom time.Time
	DateTo   time.Time
}

type MonthlyIncomeSpendingRow struct {
	Year     int32
	Month    int32
	Income   int64
	Spending int64
}

// Aggregation queries for the dashboard and reports API. All aggregates are
// scoped to accounts in a single currency (the user's budget currency) so
// foreign-currency accounts are never silently converted, and all exclude
// soft-deleted transactions.
// Income and spending per calendar month. Income is the sum of income-type
// transactions; spending is the negated sum of expense and refund transactions
// (refunds reduce spending). Transfers and adjustments are excluded from both.
func (q *Queries) MonthlyIncomeSpending(ctx context.Context, arg MonthlyIncomeSpendingParams) ([]MonthlyIncomeSpendingRow, error) {
	rows, err := q.db.Query(ctx, monthlyIncomeSpending,
		arg.UserID,
		arg.Currency,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyIncomeSpendingRow
	for rows.Next() {
		var i MonthlyIncomeSpendingRow
		if err := rows.Scan(
			&i.Year,
			&i.Month,
			&i.Income,
			&i.Spending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentTransactions = `-- name: RecentTransactions :many
SELECT id, user_id, account_id, category_id, type, status, amount, date, payee, notes, reviewed, transfer_pair_id, recurring_rule_id, import_batch_id, deleted_at, created_at, updated_at FROM transactions
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY date DESC, created_at DESC
LIMIT $2
`

type RecentTransactionsParams struct {
	UserID  uuid.UUID
	MaxRows int32
}

// Most recent non-deleted transactions for the dashboard.
func (q *Queries) RecentTransactions(ctx context.Context, arg RecentTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, recentTransactions, arg.UserID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Status,
			&i.Amount,
			&i.Date,
			&i.Payee,
			&i.Notes,
			&i.Reviewed,
			&i.TransferPairID,
			&i.RecurringRuleID,
			&i.ImportBatchID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spendingByCategoryRange = `-- name: SpendingByCategoryRange :many
SELECT x.category_id, sum(x.spend)::bigint AS spending
FROM (
    SELECT t.category_id::uuid AS category_id, -t.amount AS spend
    FROM transactions t
    JOIN accounts a ON a.id = t.account_id
    WHERE t.user_id = $1 AND t.deleted_at IS NULL
      AND t.category_id IS NOT NULL AND t.type <> 'transfer'
      AND a.currency = $2
      AND t.date BETWEEN $3 AND $4
    UNION ALL
    SELECT s.category_id, -s.amount
    FROM transaction_splits s
    JOIN transactions t ON t.id = s.transaction_id
    JOIN accounts a ON a.id = t.account_id
    WHERE s.user_id = $1 AND t.deleted_at IS NULL AND t.type <> 'transfer'
      AND a.currency = $2
      AND t.date BETWEEN $3 AND $4
) x
GROUP BY x.category_id
ORDER BY sum(x.spend) DESC
`

type SpendingByCategoryRangeParams struct {
	UserID   uuid.UUID
	Currency string
	DateFrom time.Time
	DateTo   time.Time
}

type SpendingByCategoryRangeRow struct {
	CategoryID uuid.UUID
	Spending   int64
}

// Net spending per category over a date range: categorized parent
// transactions plus split lines, transfers excluded. Same sign convention as
// CategoryMonthlySpending (spending = -amount), so refunds reduce a
// category's total.
func (q *Queries) SpendingByCategoryRange(ctx context.Context, arg SpendingByCategoryRangeParams) ([]SpendingByCategoryRangeRow, error) {
	rows, err := q.db.Query(ctx, spendingByCategoryRange,
		arg.UserID,
		arg.Currency,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpendingByCategoryRangeRow
	for rows.Next() {
		var i SpendingByCategoryRangeRow
		if err := rows.Scan(&i.CategoryID, &i.Spending); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topPayeesRange = `-- name: TopPayeesRange :many
SELECT t.payee, count(*)::bigint AS transaction_count, sum(-t.amount)::bigint AS spending
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.user_id = $1 AND t.deleted_at IS NULL
  AND t.type IN ('expense', 'refund') AND t.payee <> ''
  AND a.currency = $2
  AND t.date BETWEEN $3 AND $4
GROUP BY t.payee
ORDER BY sum(-t.amount) DESC, t.payee
LIMIT $5
`

type TopPayeesRangeParams struct {
	UserID    uuid.UUID
	Currency  string
	DateFrom  time.Time
	DateTo    time.Time
	MaxPayees int32
}

type TopPayeesRangeRow struct {
	Payee            string
	TransactionCount int64
	Spending         int64
}

// Payees ranked by net spending (expenses less refunds) over a date range.
func (q *Queries) TopPayeesRange(ctx context.Context, arg TopPayeesRangeParams) ([]TopPayeesRangeRow, error) {
	rows, err := q.db.Query(ctx, topPayeesRange,
		arg.UserID,
		arg.Currency,
		arg.DateFrom,
		arg.DateTo,
		arg.MaxPayees,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopPayeesRangeRow
	for rows.Next() {
		var i TopPayeesRangeRow
		if err := rows.Scan(&i.Payee, &i.TransactionCount, &i.Spending); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
