// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (user_id, name) VALUES ($1, $2)
ON CONFLICT (user_id, name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, user_id, name, created_at
`

type CreateTagParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.UserID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, account_id, category_id, type, status, amount, date, payee, notes, transfer_pair_id, recurring_rule_id, import_batch_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, user_id, account_id, category_id, type, status, amount, date, payee, notes, reviewed, transfer_pair_id, recurring_rule_id, import_batch_id, deleted_at, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID          uuid.UUID
	AccountID       uuid.UUID
	CategoryID      *uuid.UUID
	Type            string
	Status          string
	Amount          int64
	Date            time.Time
	Payee           string
	Notes           string
	TransferPairID  *uuid.UUID
	RecurringRuleID *uuid.UUID
	ImportBatchID   *uuid.UUID
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.Type,
		arg.Status,
		arg.Amount,
		arg.Date,
		arg.Payee,
		arg.Notes,
		arg.TransferPairID,
		arg.RecurringRuleID,
		arg.ImportBatchID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.Date,
		&i.Payee,
		&i.Notes,
		&i.Reviewed,
		&i.TransferPairID,
		&i.RecurringRuleID,
		&i.ImportBatchID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransactionSplit = `-- name: CreateTransactionSplit :one
INSERT INTO transaction_splits (user_id, transaction_id, category_id, amount, memo)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, transaction_id, category_id, amount, memo, created_at, updated_at
`

type CreateTransactionSplitParams struct {
	UserID        uuid.UUID
	TransactionID uuid.UUID
	CategoryID    uuid.UUID
	Amount        int64
	Memo          string
}

func (q *Queries) CreateTransactionSplit(ctx context.Context, arg CreateTransactionSplitParams) (TransactionSplit, error) {
	row := q.db.QueryRow(ctx, createTransactionSplit,
		arg.UserID,
		arg.TransactionID,
		arg.CategoryID,
		arg.Amount,
		arg.Memo,
	)
	var i TransactionSplit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TransactionID,
		&i.CategoryID,
		&i.Amount,
		&i.Memo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSplitsByTransaction = `-- name: DeleteSplitsByTransaction :exec
DELETE FROM transaction_splits WHERE transaction_id = $1 AND user_id = $2
`

type DeleteSplitsByTransactionParams struct {
	TransactionID uuid.UUID
	UserID        uuid.UUID
}

func (q *Queries) DeleteSplitsByTransaction(ctx context.Context, arg DeleteSplitsByTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteSplitsByTransaction, arg.TransactionID, arg.UserID)
	return err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, account_id, category_id, type, status, amount, date, payee, notes, reviewed, transfer_pair_id, recurring_rule_id, import_batch_id, deleted_at, created_at, updated_at FROM transactions WHERE id = $1 AND user_id = $2
`

type GetTransactionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.Date,
		&i.Payee,
		&i.Notes,
		&i.Reviewed,
		&i.TransferPairID,
		&i.RecurringRuleID,
		&i.ImportBatchID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSplitsByTransaction = `-- name: ListSplitsByTransaction :many
SELECT id, user_id, transaction_id, category_id, amount, memo, created_at, updated_at FROM transaction_splits WHERE transaction_id = $1 AND user_id = $2 ORDER BY created_at
`

type ListSplitsByTransactionParams struct {
	TransactionID uuid.UUID
	UserID        uuid.UUID
}

func (q *Queries) ListSplitsByTransaction(ctx context.Context, arg ListSplitsByTransactionParams) ([]TransactionSplit, error) {
	rows, err := q.db.Query(ctx, listSplitsByTransaction, arg.TransactionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionSplit
	for rows.Next() {
		var i TransactionSplit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TransactionID,
			&i.CategoryID,
			&i.Amount,
			&i.Memo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByUser = `-- name: ListTagsByUser :many
SELECT id, user_id, name, created_at FROM tags WHERE user_id = $1 ORDER BY name
`

func (q *Queries) ListTagsByUser(ctx context.Context, userID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByUser = `-- name: ListTransactionsByUser :many
SELECT id, user_id, account_id, category_id, type, status, amount, date, payee, notes, reviewed, transfer_pair_id, recurring_rule_id, import_batch_id, deleted_at, created_at, updated_at FROM transactions
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY date DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByUserParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListTransactionsByUser(ctx context.Context, arg ListTransactionsByUserParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Status,
			&i.Amount,
			&i.Date,
			&i.Payee,
			&i.Notes,
			&i.Reviewed,
			&i.TransferPairID,
			&i.RecurringRuleID,
			&i.ImportBatchID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreTransaction = `-- name: RestoreTransaction :exec
UPDATE transactions SET deleted_at = NULL, updated_at = now() WHERE id = $1 AND user_id = $2
`

type RestoreTransactionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RestoreTransaction(ctx context.Context, arg RestoreTransactionParams) error {
	_, err := q.db.Exec(ctx, restoreTransaction, arg.ID, arg.UserID)
	return err
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :exec
UPDATE transactions SET deleted_at = now(), updated_at = now() WHERE id = $1 AND user_id = $2
`

type SoftDeleteTransactionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, softDeleteTransaction, arg.ID, arg.UserID)
	return err
}

const tagTransaction = `-- name: TagTransaction :exec
INSERT INTO transaction_tags (transaction_id, tag_id, user_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type TagTransactionParams struct {
	TransactionID uuid.UUID
	TagID         uuid.UUID
	UserID        uuid.UUID
}

func (q *Queries) TagTransaction(ctx context.Context, arg TagTransactionParams) error {
	_, err := q.db.Exec(ctx, tagTransaction, arg.TransactionID, arg.TagID, arg.UserID)
	return err
}

const untagTransaction = `-- name: UntagTransaction :exec
DELETE FROM transaction_tags WHERE transaction_id = $1 AND tag_id = $2
`

type UntagTransactionParams struct {
	TransactionID uuid.UUID
	TagID         uuid.UUID
}

func (q *Queries) UntagTransaction(ctx context.Context, arg UntagTransactionParams) error {
	_, err := q.db.Exec(ctx, untagTransaction, arg.TransactionID, arg.TagID)
	return err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET account_id = $3, category_id = $4, type = $5, status = $6, amount = $7, date = $8, payee = $9, notes = $10, reviewed = $11, updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, account_id, category_id, type, status, amount, date, payee, notes, reviewed, transfer_pair_id, recurring_rule_id, import_batch_id, deleted_at, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	AccountID  uuid.UUID
	CategoryID *uuid.UUID
	Type       string
	Status     string
	Amount     int64
	Date       time.Time
	Payee      string
	Notes      string
	Reviewed   bool
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.Type,
		arg.Status,
		arg.Amount,
		arg.Date,
		arg.Payee,
		arg.Notes,
		arg.Reviewed,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.Date,
		&i.Payee,
		&i.Notes,
		&i.Reviewed,
		&i.TransferPairID,
		&i.RecurringRuleID,
		&i.ImportBatchID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
