// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, default_currency)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, locale, time_zone, first_day_of_week, default_currency, failed_login_attempts, locked_until, created_at, updated_at
`

type CreateUserParams struct {
	Email           string
	PasswordHash    string
	Name            string
	DefaultCurrency string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.DefaultCurrency,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Locale,
		&i.TimeZone,
		&i.FirstDayOfWeek,
		&i.DefaultCurrency,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, locale, time_zone, first_day_of_week, default_currency, failed_login_attempts, locked_until, created_at, updated_at FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Locale,
		&i.TimeZone,
		&i.FirstDayOfWeek,
		&i.DefaultCurrency,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, locale, time_zone, first_day_of_week, default_currency, failed_login_attempts, locked_until, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Locale,
		&i.TimeZone,
		&i.FirstDayOfWeek,
		&i.DefaultCurrency,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockUser = `-- name: LockUser :exec
UPDATE users SET locked_until = $2, updated_at = now() WHERE id = $1
`

type LockUserParams struct {
	ID          uuid.UUID
	LockedUntil *time.Time
}

func (q *Queries) LockUser(ctx context.Context, arg LockUserParams) error {
	_, err := q.db.Exec(ctx, lockUser, arg.ID, arg.LockedUntil)
	return err
}

const recordFailedLogin = `-- name: RecordFailedLogin :one
UPDATE users
SET failed_login_attempts = failed_login_attempts + 1, updated_at = now()
WHERE id = $1
RETURNING failed_login_attempts
`

func (q *Queries) RecordFailedLogin(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, recordFailedLogin, id)
	var failed_login_attempts int32
	err := row.Scan(&failed_login_attempts)
	return failed_login_attempts, err
}

const resetFailedLogins = `-- name: ResetFailedLogins :exec
UPDATE users SET failed_login_attempts = 0, locked_until = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) ResetFailedLogins(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedLogins, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name = $2, locale = $3, time_zone = $4, first_day_of_week = $5, default_currency = $6, updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, name, locale, time_zone, first_day_of_week, default_currency, failed_login_attempts, locked_until, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID              uuid.UUID
	Name            string
	Locale          string
	TimeZone        string
	FirstDayOfWeek  int16
	DefaultCurrency string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.Name,
		arg.Locale,
		arg.TimeZone,
		arg.FirstDayOfWeek,
		arg.DefaultCurrency,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Locale,
		&i.TimeZone,
		&i.FirstDayOfWeek,
		&i.DefaultCurrency,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
